=== Kory-ifcd0210/IFCD0210/MF0491_3 Cliente/UF1843/E6/Práctico/html/universoeschema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generado con XMLSpy v2019 rel. 3 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="galaxias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="tipo"/>
				<xs:element ref="posicion"/>
				<xs:element ref="magnitud"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="magnitud">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="-"/>
				<xs:enumeration value="2.9"/>
				<xs:enumeration value="9.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Galaxia Magnífica Espiral"/>
				<xs:enumeration value="Galaxia Par Ocultador"/>
				<xs:enumeration value="Galaxia Remolino"/>
				<xs:enumeration value="Galaxia Supernova 1987A"/>
				<xs:enumeration value="Galaxia del Ojo Negro"/>
				<xs:enumeration value="Galaxia del Sombrero"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="posicion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="-"/>
				<xs:enumeration value="Constelación de virgo"/>
				<xs:enumeration value="Junto a galaxia Escultor"/>
				<xs:enumeration value="constelacion dorado"/>
				<xs:enumeration value="constelación Canes Venatici"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="-"/>
				<xs:enumeration value="espiral"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="universo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="galaxias" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Kory-ifcd0210/IFCD0210/MF0491_3 Cliente/UF1842/E4/html/universo.xml
<?xml version="1.0" encoding="UTF-8"?>
<universo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/IFCD0210/MF0491_3%20Cliente/UF1841/Pr%C3%A1ctico/universoeschema.xsd">
	<galaxias>
		<nombre>Galaxia del Sombrero</nombre>
		<tipo>espiral</tipo>
		<posicion>Constelación de virgo</posicion>
		<magnitud>9.0</magnitud>
	</galaxias>
	<galaxias>
		<nombre>Galaxia del Ojo Negro</nombre>
		<tipo>espiral</tipo>
		<posicion>-</posicion>
		<magnitud>-</magnitud>
	</galaxias>
	<galaxias>
		<nombre>Galaxia Par Ocultador</nombre>
		<tipo>espiral</tipo>
		<posicion>Junto a galaxia Escultor</posicion>
		<magnitud>-</magnitud>
	</galaxias>
	<galaxias>
		<nombre>Galaxia Remolino</nombre>
		<tipo>espiral</tipo>
		<posicion>constelación Canes Venatici</posicion>
		<magnitud>9.0</magnitud>
	</galaxias>
	<galaxias>
		<nombre>Galaxia Magnífica Espiral</nombre>
		<tipo>espiral</tipo>
		<posicion>-</posicion>
		<magnitud>-</magnitud>
	</galaxias>
	<galaxias>
		<nombre>Galaxia Supernova 1987A</nombre>
		<tipo>-</tipo>
		<posicion>constelacion dorado</posicion>
		<magnitud>2.9</magnitud>
	</galaxias>
</universo>
