=== Kory-ifcd0210/IFCD0210/MF0491_3 Cliente/UF1841/E2/xml con dtd/prueba dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generado con XMLSpy v2019 rel. 3 sp1 (http://www.altova.com) -->
<!ELEMENT año (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT jugador (nombre, nacionalidad)>
<!ATTLIST jugador
	posicion (centrocampista | delantero | portero) #REQUIRED
>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT presidente (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT futbol (nombre, ciudad, año, entrenador, presidente, jugadores)>
<!ATTLIST futbol
	xsi:noNamespaceSchemaLocation CDATA #IMPLIED
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>

=== Kory-ifcd0210/IFCD0210/MF0491_3 Cliente/UF1841/E2/xml con dtd/futbol2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "C:\IFCD0210\MF0491_3 Cliente\UF1841\E2\prueba dtd.dtd">
<futbol>
	<nombre>Levante Unión Deportiva</nombre>
	<ciudad>Valencia</ciudad>
	<año>1909</año>
	<entrenador>Paco López</entrenador>
	<presidente>Francisco Catalán</presidente>
	<jugadores>
		<jugador posicion="portero">
			<nombre>Javier Jiménez</nombre>
			<nacionalidad>española</nacionalidad>
		</jugador>
		<jugador posicion="delantero">
			<nombre>Nong</nombre>
			<nacionalidad>camerunés</nacionalidad>
		</jugador>
		<jugador posicion="centrocampista">
			<nombre>Jose Luis Morales</nombre>
			<nacionalidad>Española</nacionalidad>
		</jugador>
	</jugadores>
</futbol>
